[package]
name = "aegis-ebpf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
# Internal workspace crate — never published to crates.io.
publish = false

[dependencies]
aegis-common  = { path = "../aegis-common" }
aya           = { workspace = true }
aya-log       = { workspace = true }
tokio         = { workspace = true }
tracing       = { workspace = true }
anyhow        = { workspace = true }
bytes         = { workspace = true }
chrono        = { workspace = true }
